### ISSUE TITLE
Error when typing a date with a zero

### ISSUE THREAD

**Issue by oerton42** [freddyaboulton/gradio-calendar#3]
Hello

If you click on the calendar to choose a day wich number is 0X it is ok but you can't type with your keybord to choose a 0X day. 
Days starting with 1X, 2X or 3X are working well with the keyboard

I can reproduce the error in the component gallery on the gradio website https://www.gradio.app/custom-components/gallery

Here is the error Traceback (most recent call last):
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\site-packages\gradio_calendar\calendar.py", line 55, in preprocess
    return datetime.datetime.strptime(payload, self._format_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\anaconda3\envs\AutoRadio\Lib\_strptime.py", line 349, in _strptime  
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'

**Comment by freddyaboulton** [comment]
Dang my bad, will take a look!
